# Generated by Django 6.0.1 on 2026-01-20 07:53

import core.validators
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="称号名称")),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("primary", "蓝色"),
                            ("secondary", "紫色"),
                            ("success", "绿色"),
                            ("warning", "金色"),
                            ("error", "红色"),
                        ],
                        default="primary",
                        max_length=20,
                        verbose_name="颜色风格",
                    ),
                ),
                (
                    "icon",
                    models.TextField(
                        blank=True, help_text="SVG图标代码", verbose_name="图标SVG"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="称号说明"
                    ),
                ),
            ],
            options={
                "verbose_name": "用户称号",
                "verbose_name_plural": "用户称号",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        validators=[
                            core.validators.FileValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "webp",
                                ],
                                allowed_mimetypes=[
                                    "image/jpeg",
                                    "image/png",
                                    "image/gif",
                                    "image/webp",
                                ],
                                max_size=5242880,
                            )
                        ],
                        verbose_name="头像",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        help_text="建议尺寸 800x200 像素",
                        null=True,
                        upload_to="covers/",
                        validators=[
                            core.validators.FileValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "webp",
                                ],
                                allowed_mimetypes=[
                                    "image/jpeg",
                                    "image/png",
                                    "image/gif",
                                    "image/webp",
                                ],
                                max_size=5242880,
                            )
                        ],
                        verbose_name="封面图",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(blank=True, max_length=50, verbose_name="昵称"),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="个人简介"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="个人网站")),
                ("github", models.URLField(blank=True, verbose_name="GitHub")),
                (
                    "is_banned",
                    models.BooleanField(
                        default=False,
                        help_text="封禁用户将禁止其登录系统",
                        verbose_name="是否封禁",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="users.usertitle",
                        verbose_name="称号",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verb", models.CharField(max_length=255, verbose_name="动作")),
                ("object_id", models.PositiveIntegerField()),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="已读")),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggered_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="触发者",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="接收者",
                    ),
                ),
            ],
            options={
                "verbose_name": "通知",
                "verbose_name_plural": "通知",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_profile",
                    models.BooleanField(
                        default=True,
                        help_text="允许其他人查看您的个人资料和浏览历史",
                        verbose_name="公开资料",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "明亮"),
                            ("dark", "暗黑"),
                            ("cupcake", "杯子蛋糕"),
                            ("bumblebee", "大黄蜂"),
                            ("emerald", "翡翠"),
                            ("corporate", "企业"),
                            ("synthwave", "合成波"),
                            ("retro", "复古"),
                            ("cyberpunk", "赛博朋克"),
                            ("valentine", "情人节"),
                            ("halloween", "万圣节"),
                            ("garden", "花园"),
                            ("forest", "森林"),
                            ("aqua", "水色"),
                            ("lofi", "低保真"),
                            ("pastel", "柔和"),
                            ("fantasy", "幻想"),
                            ("wireframe", "线框"),
                            ("black", "黑色"),
                            ("luxury", "奢华"),
                            ("dracula", "德古拉"),
                            ("cmyk", "CMYK"),
                            ("autumn", "秋天"),
                            ("business", "商务"),
                            ("acid", "酸性"),
                            ("lemonade", "柠檬水"),
                            ("night", "夜间"),
                            ("coffee", "咖啡"),
                            ("winter", "冬天"),
                            ("dim", "暗淡"),
                            ("nord", "诺德"),
                            ("sunset", "日落"),
                        ],
                        default="light",
                        max_length=20,
                        verbose_name="主题偏好",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preference",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户偏好",
                "verbose_name_plural": "用户偏好",
            },
        ),
    ]
