# Generated by Django 6.0 on 2026-01-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreference",
            name="theme",
            field=models.CharField(
                choices=[("light", "明亮"), ("dark", "暗黑")],
                default="light",
                max_length=20,
                verbose_name="主题偏好",
            ),
        ),
    ]
