# Generated by Django 6.0 on 2026-01-07 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_alter_user_avatar_alter_user_bio"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="接收评论回复等邮件通知",
                        verbose_name="邮件通知",
                    ),
                ),
                (
                    "public_profile",
                    models.BooleanField(
                        default=True,
                        help_text="允许其他人查看您的个人资料和浏览历史",
                        verbose_name="公开资料",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "浅色"),
                            ("dark", "深色"),
                            ("auto", "跟随系统"),
                        ],
                        default="auto",
                        max_length=10,
                        verbose_name="主题偏好",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preference",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户偏好",
                "verbose_name_plural": "用户偏好",
            },
        ),
    ]
