# Generated by Django 6.0 on 2026-01-07 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0003_userpreference"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpreference",
            name="email_notifications",
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="theme",
            field=models.CharField(
                choices=[
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("cupcake", "Cupcake"),
                    ("bumblebee", "Bumblebee"),
                    ("emerald", "Emerald"),
                    ("corporate", "Corporate"),
                    ("synthwave", "Synthwave"),
                    ("retro", "Retro"),
                    ("cyberpunk", "Cyberpunk"),
                    ("valentine", "Valentine"),
                    ("halloween", "Halloween"),
                    ("garden", "Garden"),
                    ("forest", "Forest"),
                    ("aqua", "Aqua"),
                    ("lofi", "Lofi"),
                    ("pastel", "Pastel"),
                    ("fantasy", "Fantasy"),
                    ("wireframe", "Wireframe"),
                    ("black", "Black"),
                    ("luxury", "Luxury"),
                    ("dracula", "Dracula"),
                    ("cmyk", "CMYK"),
                    ("autumn", "Autumn"),
                    ("business", "Business"),
                    ("acid", "Acid"),
                    ("lemonade", "Lemonade"),
                    ("night", "Night"),
                    ("coffee", "Coffee"),
                    ("winter", "Winter"),
                    ("dim", "Dim"),
                    ("nord", "Nord"),
                    ("sunset", "Sunset"),
                ],
                default="light",
                max_length=20,
                verbose_name="主题偏好",
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verb", models.CharField(max_length=255, verbose_name="动作")),
                ("object_id", models.PositiveIntegerField()),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="已读")),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggered_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="触发者",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="接收者",
                    ),
                ),
            ],
            options={
                "verbose_name": "通知",
                "verbose_name_plural": "通知",
                "ordering": ["-timestamp"],
            },
        ),
    ]
