# Generated by Django 6.0 on 2026-01-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_userpreference_email_notifications_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreference",
            name="theme",
            field=models.CharField(
                choices=[
                    ("light", "明亮"),
                    ("dark", "暗黑"),
                    ("cupcake", "杯子蛋糕"),
                    ("bumblebee", "大黄蜂"),
                    ("emerald", "翡翠"),
                    ("corporate", "企业"),
                    ("synthwave", "合成波"),
                    ("retro", "复古"),
                    ("cyberpunk", "赛博朋克"),
                    ("valentine", "情人节"),
                    ("halloween", "万圣节"),
                    ("garden", "花园"),
                    ("forest", "森林"),
                    ("aqua", "水色"),
                    ("lofi", "低保真"),
                    ("pastel", "柔和"),
                    ("fantasy", "幻想"),
                    ("wireframe", "线框"),
                    ("black", "黑色"),
                    ("luxury", "奢华"),
                    ("dracula", "德古拉"),
                    ("cmyk", "CMYK"),
                    ("autumn", "秋天"),
                    ("business", "商务"),
                    ("acid", "酸性"),
                    ("lemonade", "柠檬水"),
                    ("night", "夜间"),
                    ("coffee", "咖啡"),
                    ("winter", "冬天"),
                    ("dim", "暗淡"),
                    ("nord", "诺德"),
                    ("sunset", "日落"),
                ],
                default="light",
                max_length=20,
                verbose_name="主题偏好",
            ),
        ),
    ]
