# Generated by Django 6.0 on 2026-01-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_userpreference_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="github",
            field=models.URLField(blank=True, verbose_name="GitHub"),
        ),
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, max_length=50, verbose_name="昵称"),
        ),
        migrations.AddField(
            model_name="user",
            name="website",
            field=models.URLField(blank=True, verbose_name="个人网站"),
        ),
    ]
