# Generated by Django 6.0 on 2026-01-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_github_user_nickname_user_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="建议尺寸 800x200 像素",
                null=True,
                upload_to="covers/",
                verbose_name="封面图",
            ),
        ),
    ]
