# Generated by Django 6.0 on 2026-01-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_cover_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="名称")),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("primary", "Primary (Indigo)"),
                            ("secondary", "Secondary (Pink)"),
                            ("accent", "Accent (Cyan)"),
                            ("neutral", "Neutral (Grey)"),
                            ("info", "Info (Blue)"),
                            ("success", "Success (Green)"),
                            ("warning", "Warning (Yellow)"),
                            ("error", "Error (Red)"),
                        ],
                        default="neutral",
                        max_length=20,
                        verbose_name="颜色",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="描述"),
                ),
            ],
            options={
                "verbose_name": "用户标签",
                "verbose_name_plural": "用户标签",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="users.userlabel",
                verbose_name="标签",
            ),
        ),
    ]
