# Generated by Django 6.0 on 2026-01-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="navigation",
            options={
                "ordering": ["order"],
                "verbose_name": "导航菜单",
                "verbose_name_plural": "导航菜单",
            },
        ),
        migrations.AlterModelOptions(
            name="sitesettings",
            options={"verbose_name": "站点设置", "verbose_name_plural": "站点设置"},
        ),
        migrations.AlterField(
            model_name="navigation",
            name="order",
            field=models.IntegerField(default=0, verbose_name="排序"),
        ),
        migrations.AlterField(
            model_name="navigation",
            name="title",
            field=models.CharField(max_length=100, verbose_name="标题"),
        ),
        migrations.AlterField(
            model_name="navigation",
            name="url",
            field=models.CharField(max_length=200, verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="footer_text",
            field=models.TextField(
                default="© 2026 Rosetta Blog", verbose_name="页脚文本"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="github_url",
            field=models.URLField(blank=True, verbose_name="GitHub 链接"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_header",
            field=models.CharField(
                default="Rosetta Dashboard", max_length=200, verbose_name="网站头部"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_title",
            field=models.CharField(
                default="Rosetta Blog", max_length=200, verbose_name="网站标题"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="twitter_url",
            field=models.URLField(blank=True, verbose_name="Twitter 链接"),
        ),
    ]
