# Generated by Django 6.0 on 2026-01-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_navigation_options_alter_sitesettings_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="about_content",
            field=models.TextField(
                default="欢迎来到 Rosetta 博客。我们热衷于分享技术、编程和设计方面的知识与见解。",
                help_text="支持 HTML",
                verbose_name="关于页面内容",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_content",
            field=models.TextField(
                default="可以通过以下方式联系我们...",
                help_text="支持 HTML",
                verbose_name="联系我们页面内容",
            ),
        ),
    ]
