# Generated by Django 6.0 on 2026-01-07 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="about_content",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="contact_content",
        ),
    ]
