# Generated by Django 6.0 on 2026-01-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_sitesettings_about_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FriendLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="网站名称")),
                ("url", models.URLField(verbose_name="网站链接")),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="描述"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="friend_links/",
                        verbose_name="Logo",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否显示"),
                ),
            ],
            options={
                "verbose_name": "友情链接",
                "verbose_name_plural": "友情链接",
                "ordering": ["order", "id"],
            },
        ),
    ]
