# Generated by Django 6.0 on 2026-01-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_friendlink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendlink",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="friend_links/", verbose_name="标志"
            ),
        ),
    ]
