# Generated by Django 6.0 on 2026-01-13 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_friendlink_logo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SiteSettings",
        ),
    ]
