# Generated by Django 6.0 on 2026-01-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_delete_sitesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="navigation",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否显示"),
        ),
    ]
