# Generated by Django 6.0 on 2026-01-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_navigation_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="navigation",
            name="location",
            field=models.CharField(
                choices=[
                    ("header", "顶部导航"),
                    ("footer", "底部链接"),
                    ("sidebar", "侧边栏"),
                ],
                default="header",
                max_length=20,
                verbose_name="位置",
            ),
        ),
    ]
