# Generated by Django 6.0 on 2026-01-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendlink",
            name="description_en",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="描述"
            ),
        ),
        migrations.AddField(
            model_name="friendlink",
            name="description_ja",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="描述"
            ),
        ),
        migrations.AddField(
            model_name="friendlink",
            name="description_zh_hans",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="描述"
            ),
        ),
        migrations.AddField(
            model_name="friendlink",
            name="description_zh_hant",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="描述"
            ),
        ),
        migrations.AddField(
            model_name="friendlink",
            name="name_en",
            field=models.CharField(max_length=100, null=True, verbose_name="网站名称"),
        ),
        migrations.AddField(
            model_name="friendlink",
            name="name_ja",
            field=models.CharField(max_length=100, null=True, verbose_name="网站名称"),
        ),
        migrations.AddField(
            model_name="friendlink",
            name="name_zh_hans",
            field=models.CharField(max_length=100, null=True, verbose_name="网站名称"),
        ),
        migrations.AddField(
            model_name="friendlink",
            name="name_zh_hant",
            field=models.CharField(max_length=100, null=True, verbose_name="网站名称"),
        ),
        migrations.AddField(
            model_name="navigation",
            name="title_en",
            field=models.CharField(max_length=100, null=True, verbose_name="标题"),
        ),
        migrations.AddField(
            model_name="navigation",
            name="title_ja",
            field=models.CharField(max_length=100, null=True, verbose_name="标题"),
        ),
        migrations.AddField(
            model_name="navigation",
            name="title_zh_hans",
            field=models.CharField(max_length=100, null=True, verbose_name="标题"),
        ),
        migrations.AddField(
            model_name="navigation",
            name="title_zh_hant",
            field=models.CharField(max_length=100, null=True, verbose_name="标题"),
        ),
        migrations.AddField(
            model_name="page",
            name="content_en",
            field=models.TextField(null=True, verbose_name="内容"),
        ),
        migrations.AddField(
            model_name="page",
            name="content_ja",
            field=models.TextField(null=True, verbose_name="内容"),
        ),
        migrations.AddField(
            model_name="page",
            name="content_zh_hans",
            field=models.TextField(null=True, verbose_name="内容"),
        ),
        migrations.AddField(
            model_name="page",
            name="content_zh_hant",
            field=models.TextField(null=True, verbose_name="内容"),
        ),
        migrations.AddField(
            model_name="page",
            name="title_en",
            field=models.CharField(max_length=200, null=True, verbose_name="标题"),
        ),
        migrations.AddField(
            model_name="page",
            name="title_ja",
            field=models.CharField(max_length=200, null=True, verbose_name="标题"),
        ),
        migrations.AddField(
            model_name="page",
            name="title_zh_hans",
            field=models.CharField(max_length=200, null=True, verbose_name="标题"),
        ),
        migrations.AddField(
            model_name="page",
            name="title_zh_hant",
            field=models.CharField(max_length=200, null=True, verbose_name="标题"),
        ),
        migrations.AddField(
            model_name="searchplaceholder",
            name="text_en",
            field=models.CharField(
                help_text="例如：搜索 Django...",
                max_length=100,
                null=True,
                verbose_name="占位符文本",
            ),
        ),
        migrations.AddField(
            model_name="searchplaceholder",
            name="text_ja",
            field=models.CharField(
                help_text="例如：搜索 Django...",
                max_length=100,
                null=True,
                verbose_name="占位符文本",
            ),
        ),
        migrations.AddField(
            model_name="searchplaceholder",
            name="text_zh_hans",
            field=models.CharField(
                help_text="例如：搜索 Django...",
                max_length=100,
                null=True,
                verbose_name="占位符文本",
            ),
        ),
        migrations.AddField(
            model_name="searchplaceholder",
            name="text_zh_hant",
            field=models.CharField(
                help_text="例如：搜索 Django...",
                max_length=100,
                null=True,
                verbose_name="占位符文本",
            ),
        ),
    ]
