# Generated by Django 6.0 on 2026-01-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_friendlink_description_en_friendlink_description_ja_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendlink",
            name="target_blank",
            field=models.BooleanField(default=False, verbose_name="新窗口打开"),
        ),
        migrations.AddField(
            model_name="navigation",
            name="target_blank",
            field=models.BooleanField(default=False, verbose_name="新窗口打开"),
        ),
    ]
