"""
Django settings for Rosetta project.

Generated by 'django-admin startproject' using Django 6.0.
"""

import os
from pathlib import Path
from datetime import timedelta

# 构建项目内的路径: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ==============================================================================
# 核心安全设置 (Core Security Settings)
# ==============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
# 在生产环境中，请确保 SECRET_KEY 保密且唯一。建议使用环境变量获取。
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-598u(^sv4vtl1)@)uxmsz%&oeoxtgau09)5en^0#n!uz63$o@(",
)

# SECURITY WARNING: don't run with debug turned on in production!
# 生产环境请务必设置为 False
DEBUG = True

ALLOWED_HOSTS = []


# ==============================================================================
# 应用配置 (Application Definition)
# ==============================================================================

INSTALLED_APPS = [
    "administration",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party apps (第三方应用)
    "guardian",               # 对象级权限管理
    "tailwind",               # Tailwind CSS 集成
    "theme",                  # 前端主题应用
    "django_browser_reload",  # 开发环境自动刷新
    "django_htmx",            # HTMX 支持
    "django_filters",         # 过滤器
    "import_export",          # 数据导入导出
    "captcha",                # 验证码
    "simple_history",         # 模型变更历史
    "rest_framework",         # REST API
    "rest_framework_simplejwt", # JWT 认证
    # Newly Added Feature Apps
    "imagekit",               # 图片处理
    "watson",                 # 全文搜索
    "compressor",             # 静态资源压缩
    "meta",                   # SEO Meta 标签
    "constance",              # 动态配置
    "constance.backends.database",
    "django.contrib.sites",   # 站点框架 (Required for comments, sitemaps)
    "django.contrib.sitemaps",# 站点地图
    "chartjs",                # 图表库
    # Local apps (本地应用)
    "blog.apps.BlogConfig",   # 博客核心
    "users.apps.UsersConfig", # 用户系统
    "core.apps.CoreConfig",   # 核心功能
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",             # HTMX 中间件
    "simple_history.middleware.HistoryRequestMiddleware", # 历史记录中间件
    "watson.middleware.SearchContextMiddleware",         # Watson 搜索中间件
]

# 开发环境添加浏览器自动刷新中间件
if DEBUG:
    MIDDLEWARE += [
        "django_browser_reload.middleware.BrowserReloadMiddleware",
    ]

ROOT_URLCONF = "Rosetta.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"], # 全局模板目录
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.site_settings", # 自定义站点设置
                "constance.context_processors.config",   # 动态配置
            ],
        },
    },
]

WSGI_APPLICATION = "Rosetta.wsgi.application"


# ==============================================================================
# 数据库 (Database)
# ==============================================================================
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# ==============================================================================
# 认证与用户 (Authentication & Users)
# ==============================================================================

# 自定义用户模型
AUTH_USER_MODEL = "users.User"

# 认证后端
AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",   # 默认后端
    "guardian.backends.ObjectPermissionBackend",   # 对象级权限
)

# 密码验证策略
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# 登录重定向配置
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
LOGIN_URL = "users:login"


# ==============================================================================
# 国际化与本地化 (I18N & L10N)
# ==============================================================================

LANGUAGE_CODE = "zh-hans" # 简体中文
TIME_ZONE = "Asia/Shanghai" # 上海时间
USE_I18N = True
USE_TZ = True


# ==============================================================================
# 静态文件与媒体文件 (Static & Media)
# ==============================================================================

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"  # 收集静态文件的目录

# 静态文件查找路径
STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "compressor.finders.CompressorFinder", # Compressor 查找器
)

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media" # 用户上传文件存储目录


# ==============================================================================
# 第三方库配置 (Third-Party Configurations)
# ==============================================================================

# 1. Tailwind CSS
TAILWIND_APP_NAME = "theme"
NPM_BIN_PATH = "C:\\Program Files\\nodejs\\npm.cmd" # 请根据实际环境修改

# 2. Django Sites Framework
SITE_ID = 1

# 3. DRF & JWT Settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    )
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": True,
}

# 4. Django Constance (动态配置)
CONSTANCE_BACKEND = "constance.backends.database.DatabaseBackend"
CONSTANCE_CONFIG = {
    "SITE_NAME": ("Rosetta Blog", "站点名称"),
    "SITE_DESCRIPTION": ("A modern Django blog.", "站点描述"),
    "SITE_HEADER": ("Rosetta Dashboard", "后台头部标题"),
    "FOOTER_TEXT": ("© 2026 Rosetta Blog", "页脚文本"),
    "DASHBOARD_WELCOME_TEXT": ("这里是您的站点概览，祝您有美好的一天。", "仪表盘欢迎语"),
    "ADMIN_NAVBAR_TITLE": ("Rosetta 管理后台", "后台导航栏标题"),
    "GITHUB_URL": ("", "GitHub 链接"),
    "TWITTER_URL": ("", "Twitter 链接"),
    "MAINTENANCE_MODE": (False, "开启维护模式"),
    "ENABLE_COMMENTS": (True, "开启评论功能"),
}
CONSTANCE_CONFIG_FIELDSETS = {
    "General Options": (
        "SITE_NAME",
        "SITE_DESCRIPTION",
        "SITE_HEADER",
        "ADMIN_NAVBAR_TITLE",
        "DASHBOARD_WELCOME_TEXT",
        "FOOTER_TEXT",
    ),
    "Social Links": ("GITHUB_URL", "TWITTER_URL"),
    "Feature Switches": ("MAINTENANCE_MODE", "ENABLE_COMMENTS"),
}

# 5. Django Compressor
COMPRESS_ENABLED = not DEBUG  # 开发环境建议关闭压缩，避免样式加载问题
COMPRESS_OFFLINE = False

# 6. Django Meta
META_SITE_PROTOCOL = "http"
META_SITE_DOMAIN = "localhost:8000"
META_USE_OG_PROPERTIES = True
META_USE_TWITTER_PROPERTIES = True

# 7. Loguru Logging (日志系统)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "intercept": {
            "level": "INFO",
            "class": "core.logging.InterceptHandler",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["intercept"],
            "level": "INFO",
            "propagate": True,
        },
        "django.db.backends": {
            "handlers": ["intercept"],
            "level": "WARNING",  # Reduce noise
            "propagate": False,
        },
    },
}

# Configure Loguru file logging
LOG_DIR = BASE_DIR / "logs"
if not LOG_DIR.exists():
    try:
        LOG_DIR.mkdir(parents=True, exist_ok=True)
    except Exception:
        pass

if not DEBUG:
    from loguru import logger
    logger.add(
        LOG_DIR / "rosetta.log",
        rotation="10 MB",
        retention="30 days",
        level="WARNING",
        compression="zip",
        enqueue=True,
    )
else:
    from loguru import logger
    # 开发环境使用 debug.log
    logger.add(
        LOG_DIR / "debug.log",
        level="DEBUG",
    )
