"""
Django settings for Rosetta project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-598u(^sv4vtl1)@)uxmsz%&oeoxtgau09)5en^0#n!uz63$o@(",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "administration",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party apps
    "guardian",
    "tailwind",
    "theme",
    "django_browser_reload",
    "django_htmx",
    "django_filters",
    "import_export",
    "captcha",
    "simple_history",
    "rest_framework",
    "rest_framework_simplejwt",
    # Newly Added Feature Apps
    "imagekit",
    "watson",
    "compressor",
    "meta",
    "constance",
    "constance.backends.database",
    "django.contrib.sites",  # Required for comments, sitemaps
    "django.contrib.sitemaps",
    "chartjs",  # django-chartjs
    # Local apps
    "blog.apps.BlogConfig",
    "users.apps.UsersConfig",
    "core.apps.CoreConfig",
]

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "guardian.backends.ObjectPermissionBackend",
)

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "watson.middleware.SearchContextMiddleware",  # Watson Search
]

AUTH_USER_MODEL = "users.User"

ROOT_URLCONF = "Rosetta.urls"

# Sites Framework
SITE_ID = 1

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.site_settings",
                "constance.context_processors.config",
            ],
        },
    },
]

WSGI_APPLICATION = "Rosetta.wsgi.application"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
LOGIN_URL = "users:login"


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"  # Required for compressor

STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "compressor.finders.CompressorFinder",
)

TAILWIND_APP_NAME = "theme"

if DEBUG:
    # Add django_browser_reload middleware only in DEBUG mode
    MIDDLEWARE += [
        "django_browser_reload.middleware.BrowserReloadMiddleware",
    ]

NPM_BIN_PATH = "C:\\Program Files\\nodejs\\npm.cmd"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

from django.urls import reverse_lazy
from django.templatetags.static import static

# DRF & JWT Settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    )
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": True,
}

# --- Feature Packages Configuration ---

# 1. Django Constance (Dynamic Settings)
CONSTANCE_BACKEND = "constance.backends.database.DatabaseBackend"
CONSTANCE_CONFIG = {
    "SITE_NAME": ("Rosetta Blog", "站点名称"),
    "SITE_DESCRIPTION": ("A modern Django blog.", "站点描述"),
    "SITE_HEADER": ("Rosetta Dashboard", "后台头部标题"),
    "FOOTER_TEXT": ("© 2026 Rosetta Blog", "页脚文本"),
    "DASHBOARD_WELCOME_TEXT": ("这里是您的站点概览，祝您有美好的一天。", "仪表盘欢迎语"),
    "ADMIN_NAVBAR_TITLE": ("Rosetta 管理后台", "后台导航栏标题"),
    "GITHUB_URL": ("", "GitHub 链接"),
    "TWITTER_URL": ("", "Twitter 链接"),
    "MAINTENANCE_MODE": (False, "开启维护模式"),
    "ENABLE_COMMENTS": (True, "开启评论功能"),
}
CONSTANCE_CONFIG_FIELDSETS = {
    "General Options": (
        "SITE_NAME",
        "SITE_DESCRIPTION",
        "SITE_HEADER",
        "ADMIN_NAVBAR_TITLE",
        "DASHBOARD_WELCOME_TEXT",
        "FOOTER_TEXT",
    ),
    "Social Links": ("GITHUB_URL", "TWITTER_URL"),
    "Feature Switches": ("MAINTENANCE_MODE", "ENABLE_COMMENTS"),
}

# 3. Django Compressor
COMPRESS_ENABLED = not DEBUG  # 开发环境建议关闭压缩，避免样式加载问题
COMPRESS_OFFLINE = False

# 4. Django Meta
META_SITE_PROTOCOL = "http"
META_SITE_DOMAIN = "localhost:8000"
META_USE_OG_PROPERTIES = True
META_USE_TWITTER_PROPERTIES = True

# 5. Loguru Logging
# Redirect standard logging to Loguru
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "intercept": {
            "level": "INFO",
            "class": "core.logging.InterceptHandler",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["intercept"],
            "level": "INFO",
            "propagate": True,
        },
        "django.db.backends": {
            "handlers": ["intercept"],
            "level": "WARNING",  # Reduce noise
            "propagate": False,
        },
    },
}

# Configure Loguru file logging
# Ensure logs directory exists
LOG_DIR = BASE_DIR / "logs"
if not LOG_DIR.exists():
    try:
        LOG_DIR.mkdir(parents=True, exist_ok=True)
    except Exception:
        pass  # Fail silently if permissions issue

if not DEBUG:
    from loguru import logger

    logger.add(
        LOG_DIR / "rosetta.log",
        rotation="10 MB",
        retention="30 days",
        level="WARNING",
        compression="zip",
        enqueue=True,
    )
else:
    # Optional: Add a debug log file for development
    from loguru import logger

    # Avoid using rotation on Windows in DEBUG mode to prevent PermissionError [WinError 32]
    # when multiple processes (like Django auto-reloader) access the file.
    logger.add(
        LOG_DIR / "debug.log",
        level="DEBUG",
        enqueue=True,
    )

# Security & Performance
X_FRAME_OPTIONS = "SAMEORIGIN"
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB

# Email Settings
# QQ Mail Configuration
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.qq.com"
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
EMAIL_HOST_USER = "choyeon@foxmail.com"
EMAIL_HOST_PASSWORD = "vluussppnkbtbcdf"  # QQ Mail Authorization Code
DEFAULT_FROM_EMAIL = f"Rosetta Blog <{EMAIL_HOST_USER}>"
