# Generated by Django 6.0 on 2026-01-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_published_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-is_pinned", "-published_at", "-created_at"],
                "verbose_name": "文章",
                "verbose_name_plural": "文章",
            },
        ),
        migrations.RenameIndex(
            model_name="post",
            new_name="blog_post_status_5b2843_idx",
            old_name="blog_post_status_published_at_idx",
        ),
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                default="#64748B", max_length=20, verbose_name="颜色"
            ),
        ),
    ]
