# Generated by Django 6.0 on 2026-01-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="覆盖默认的描述，建议 160 字以内",
                max_length=200,
                verbose_name="Meta 描述",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="逗号分隔的关键词",
                max_length=200,
                verbose_name="Meta 关键词",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="覆盖默认的标题，用于搜索引擎显示",
                max_length=200,
                verbose_name="Meta 标题",
            ),
        ),
    ]
