# Generated by Django 6.0 on 2026-01-27 09:00

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_meta_description_post_meta_keywords_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="categories/",
                validators=[
                    core.validators.FileValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif", "webp"],
                        allowed_mimetypes=[
                            "image/jpeg",
                            "image/png",
                            "image/gif",
                            "image/webp",
                        ],
                        max_size=5242880,
                    )
                ],
                verbose_name="封面图",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="blog.category",
                verbose_name="父分类",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="audio",
            field=models.FileField(
                blank=True, null=True, upload_to="posts/audio/", verbose_name="音频"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="source",
            field=models.CharField(
                blank=True, default="原创", max_length=50, verbose_name="来源"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="source_url",
            field=models.URLField(blank=True, verbose_name="来源链接"),
        ),
        migrations.AddField(
            model_name="post",
            name="subtitle",
            field=models.CharField(blank=True, max_length=200, verbose_name="副标题"),
        ),
        migrations.AddField(
            model_name="post",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="posts/video/", verbose_name="视频"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="外部视频链接 (YouTube, Bilibili)",
                verbose_name="视频链接",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Material Symbols 图标代码",
                max_length=50,
                verbose_name="图标",
            ),
        ),
    ]
