# Generated by Django 6.0 on 2026-01-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_category_cover_image_category_parent_post_audio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="描述"),
        ),
        migrations.AddField(
            model_name="category",
            name="description_ja",
            field=models.TextField(blank=True, null=True, verbose_name="描述"),
        ),
        migrations.AddField(
            model_name="category",
            name="description_zh_hans",
            field=models.TextField(blank=True, null=True, verbose_name="描述"),
        ),
        migrations.AddField(
            model_name="category",
            name="description_zh_hant",
            field=models.TextField(blank=True, null=True, verbose_name="描述"),
        ),
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(max_length=100, null=True, verbose_name="名称"),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ja",
            field=models.CharField(max_length=100, null=True, verbose_name="名称"),
        ),
        migrations.AddField(
            model_name="category",
            name="name_zh_hans",
            field=models.CharField(max_length=100, null=True, verbose_name="名称"),
        ),
        migrations.AddField(
            model_name="category",
            name="name_zh_hant",
            field=models.CharField(max_length=100, null=True, verbose_name="名称"),
        ),
        migrations.AddField(
            model_name="post",
            name="content_en",
            field=models.TextField(null=True, verbose_name="内容"),
        ),
        migrations.AddField(
            model_name="post",
            name="content_ja",
            field=models.TextField(null=True, verbose_name="内容"),
        ),
        migrations.AddField(
            model_name="post",
            name="content_zh_hans",
            field=models.TextField(null=True, verbose_name="内容"),
        ),
        migrations.AddField(
            model_name="post",
            name="content_zh_hant",
            field=models.TextField(null=True, verbose_name="内容"),
        ),
        migrations.AddField(
            model_name="post",
            name="excerpt_en",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="摘要"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="excerpt_ja",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="摘要"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="excerpt_zh_hans",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="摘要"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="excerpt_zh_hant",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="摘要"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="subtitle_en",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="副标题"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="subtitle_ja",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="副标题"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="subtitle_zh_hans",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="副标题"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="subtitle_zh_hant",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="副标题"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="title_en",
            field=models.CharField(max_length=200, null=True, verbose_name="标题"),
        ),
        migrations.AddField(
            model_name="post",
            name="title_ja",
            field=models.CharField(max_length=200, null=True, verbose_name="标题"),
        ),
        migrations.AddField(
            model_name="post",
            name="title_zh_hans",
            field=models.CharField(max_length=200, null=True, verbose_name="标题"),
        ),
        migrations.AddField(
            model_name="post",
            name="title_zh_hant",
            field=models.CharField(max_length=200, null=True, verbose_name="标题"),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_en",
            field=models.CharField(max_length=100, null=True, verbose_name="名称"),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_ja",
            field=models.CharField(max_length=100, null=True, verbose_name="名称"),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_zh_hans",
            field=models.CharField(max_length=100, null=True, verbose_name="名称"),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_zh_hant",
            field=models.CharField(max_length=100, null=True, verbose_name="名称"),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Material Symbols 图标代码",
                max_length=50,
                verbose_name="图标",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="icon",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Material Symbols 图标代码",
                max_length=50,
                verbose_name="图标",
            ),
        ),
    ]
