# Generated by Django 6.0 on 2026-01-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_category_description_en_category_description_ja_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="meta_description_en",
            field=models.CharField(
                blank=True,
                help_text="覆盖默认的描述，建议 160 字以内",
                max_length=200,
                null=True,
                verbose_name="Meta 描述",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="meta_description_ja",
            field=models.CharField(
                blank=True,
                help_text="覆盖默认的描述，建议 160 字以内",
                max_length=200,
                null=True,
                verbose_name="Meta 描述",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="meta_description_zh_hans",
            field=models.CharField(
                blank=True,
                help_text="覆盖默认的描述，建议 160 字以内",
                max_length=200,
                null=True,
                verbose_name="Meta 描述",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="meta_description_zh_hant",
            field=models.CharField(
                blank=True,
                help_text="覆盖默认的描述，建议 160 字以内",
                max_length=200,
                null=True,
                verbose_name="Meta 描述",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="meta_keywords_en",
            field=models.CharField(
                blank=True,
                help_text="逗号分隔的关键词",
                max_length=200,
                null=True,
                verbose_name="Meta 关键词",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="meta_keywords_ja",
            field=models.CharField(
                blank=True,
                help_text="逗号分隔的关键词",
                max_length=200,
                null=True,
                verbose_name="Meta 关键词",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="meta_keywords_zh_hans",
            field=models.CharField(
                blank=True,
                help_text="逗号分隔的关键词",
                max_length=200,
                null=True,
                verbose_name="Meta 关键词",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="meta_keywords_zh_hant",
            field=models.CharField(
                blank=True,
                help_text="逗号分隔的关键词",
                max_length=200,
                null=True,
                verbose_name="Meta 关键词",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="meta_title_en",
            field=models.CharField(
                blank=True,
                help_text="覆盖默认的标题，用于搜索引擎显示",
                max_length=200,
                null=True,
                verbose_name="Meta 标题",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="meta_title_ja",
            field=models.CharField(
                blank=True,
                help_text="覆盖默认的标题，用于搜索引擎显示",
                max_length=200,
                null=True,
                verbose_name="Meta 标题",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="meta_title_zh_hans",
            field=models.CharField(
                blank=True,
                help_text="覆盖默认的标题，用于搜索引擎显示",
                max_length=200,
                null=True,
                verbose_name="Meta 标题",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="meta_title_zh_hant",
            field=models.CharField(
                blank=True,
                help_text="覆盖默认的标题，用于搜索引擎显示",
                max_length=200,
                null=True,
                verbose_name="Meta 标题",
            ),
        ),
    ]
