# Generated by Django 6.0 on 2026-01-29 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_post_meta_description_en_post_meta_description_ja_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="parent",
        ),
    ]
