# Generated by Django 6.0 on 2026-01-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscriber",
        ),
        migrations.RemoveField(
            model_name="post",
            name="notification_sent",
        ),
    ]
