# Generated by Django 6.0 on 2026-01-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_category_options_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="password",
            field=models.CharField(
                blank=True,
                help_text="设置此密码后，访问文章需要输入密码",
                max_length=50,
                verbose_name="访问密码",
            ),
        ),
    ]
