# Generated by Django 6.0 on 2026-01-07 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_comment_active_alter_comment_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("draft", "草稿"), ("published", "已发布")],
                db_index=True,
                default="draft",
                max_length=10,
                verbose_name="状态",
            ),
        ),
    ]
