# Generated by Django 6.0 on 2026-01-13 17:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_comment_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="邮箱地址"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否订阅"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="订阅时间"),
                ),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                "verbose_name": "订阅者",
                "verbose_name_plural": "订阅者",
                "ordering": ["-created_at"],
            },
        ),
    ]
