# Generated by Django 6.0 on 2026-01-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_subscriber"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="notification_sent",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="已发送通知"
            ),
        ),
    ]
