# Generated by Django 6.0 on 2026-01-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_post_notification_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="color",
            field=models.CharField(
                choices=[
                    ("primary", "Primary (Indigo)"),
                    ("secondary", "Secondary (Pink)"),
                    ("accent", "Accent (Cyan)"),
                    ("neutral", "Neutral (Grey)"),
                    ("info", "Info (Blue)"),
                    ("success", "Success (Green)"),
                    ("warning", "Warning (Yellow)"),
                    ("error", "Error (Red)"),
                ],
                default="neutral",
                max_length=20,
                verbose_name="颜色",
            ),
        ),
    ]
