# Generated by Django 6.0 on 2026-01-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_tag_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否可见"),
        ),
    ]
