# Generated by Django 6.0 on 2026-01-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_userpreference_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertitle",
            name="color",
            field=models.CharField(
                default="#3B82F6", max_length=20, verbose_name="颜色风格"
            ),
        ),
    ]
