# Generated by Django 6.0 on 2026-01-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_usertitle_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertitle",
            name="description_en",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="称号说明"
            ),
        ),
        migrations.AddField(
            model_name="usertitle",
            name="description_ja",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="称号说明"
            ),
        ),
        migrations.AddField(
            model_name="usertitle",
            name="description_zh_hans",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="称号说明"
            ),
        ),
        migrations.AddField(
            model_name="usertitle",
            name="description_zh_hant",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="称号说明"
            ),
        ),
        migrations.AddField(
            model_name="usertitle",
            name="name_en",
            field=models.CharField(max_length=50, null=True, verbose_name="称号名称"),
        ),
        migrations.AddField(
            model_name="usertitle",
            name="name_ja",
            field=models.CharField(max_length=50, null=True, verbose_name="称号名称"),
        ),
        migrations.AddField(
            model_name="usertitle",
            name="name_zh_hans",
            field=models.CharField(max_length=50, null=True, verbose_name="称号名称"),
        ),
        migrations.AddField(
            model_name="usertitle",
            name="name_zh_hant",
            field=models.CharField(max_length=50, null=True, verbose_name="称号名称"),
        ),
    ]
