# Generated by Django 5.2 on 2025-05-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('email', '电子邮件'), ('phone', '电话'), ('wechat', '微信'), ('qq', 'QQ'), ('address', '地址'), ('other', '其他')], max_length=20, unique=True, verbose_name='联系方式类型')),
                ('method', models.CharField(max_length=50, verbose_name='联系方式')),
                ('value', models.CharField(max_length=100, verbose_name='联系值')),
                ('icon', models.CharField(max_length=50, verbose_name='图标类名')),
                ('color', models.CharField(default='blue', max_length=20, verbose_name='颜色')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '联系方式',
                'verbose_name_plural': '联系方式',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('blog', '博客'), ('portfolio', '作品集'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('other', '其他')], max_length=20, unique=True, verbose_name='链接类型')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('url', models.URLField(verbose_name='链接地址')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='用户名')),
                ('icon', models.CharField(help_text='Font Awesome图标类名', max_length=50, verbose_name='图标类名')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('is_navigation', models.BooleanField(default=False, help_text='是否显示在导航栏上方', verbose_name='导航链接')),
            ],
            options={
                'verbose_name': '链接',
                'verbose_name_plural': '链接',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('title', models.CharField(max_length=100, verbose_name='职位头衔')),
                ('avatar', models.ImageField(upload_to='avatars/', verbose_name='头像')),
                ('about_me', models.TextField(verbose_name='关于我')),
            ],
            options={
                'verbose_name': '个人资料',
                'verbose_name_plural': '个人资料',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('color', models.CharField(choices=[('blue', '蓝色'), ('green', '绿色'), ('purple', '紫色'), ('red', '红色'), ('yellow', '黄色'), ('pink', '粉色')], default='blue', max_length=20, verbose_name='颜色')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '技能标签',
                'verbose_name_plural': '技能标签',
                'ordering': ['order'],
            },
        ),
    ]
