# Generated by Django 5.2 on 2025-05-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='color',
            field=models.CharField(choices=[('blue', '蓝色 (bg-blue-500)'), ('red', '红色 (bg-red-500)'), ('green', '绿色 (bg-green-500)'), ('yellow', '黄色 (bg-yellow-500)'), ('purple', '紫色 (bg-purple-500)'), ('pink', '粉色 (bg-pink-500)'), ('indigo', '靛蓝 (bg-indigo-500)'), ('gray', '灰色 (bg-gray-500)'), ('teal', '蓝绿 (bg-teal-500)'), ('orange', '橙色 (bg-orange-500)'), ('cyan', '青色 (bg-cyan-500)'), ('lime', '石灰 (bg-lime-500)'), ('amber', '琥珀 (bg-amber-500)'), ('emerald', '祖母绿 (bg-emerald-500)'), ('fuchsia', '紫红 (bg-fuchsia-500)'), ('rose', '玫瑰 (bg-rose-500)'), ('sky', '天蓝 (bg-sky-500)'), ('violet', '紫罗兰 (bg-violet-500)')], default='blue', max_length=20, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='icon',
            field=models.CharField(help_text='Font Awesome图标类名，如 fa-envelope、fa-phone、fa-weixin 等', max_length=50, verbose_name='图标类名'),
        ),
        migrations.AlterField(
            model_name='link',
            name='icon',
            field=models.CharField(help_text='Font Awesome图标类名，如 fa-github、fa-linkedin 等', max_length=50, verbose_name='图标类名'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='color',
            field=models.CharField(choices=[('blue', '蓝色'), ('green', '绿色'), ('purple', '紫色'), ('red', '红色'), ('yellow', '黄色'), ('pink', '粉色'), ('indigo', '靛蓝'), ('gray', '灰色'), ('teal', '蓝绿'), ('orange', '橙色'), ('cyan', '青色'), ('lime', '石灰'), ('amber', '琥珀'), ('emerald', '祖母绿'), ('fuchsia', '紫红'), ('rose', '玫瑰'), ('sky', '天蓝'), ('violet', '紫罗兰')], default='blue', max_length=20, verbose_name='颜色'),
        ),
    ]
