# Generated by Django 5.2 on 2025-05-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_color_alter_contact_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('email', '电子邮件'), ('phone', '电话'), ('wechat', '微信'), ('qq', 'QQ'), ('telegram', 'Telegram'), ('other', '其他')], max_length=20, unique=True, verbose_name='联系方式类型'),
        ),
    ]
