# Generated by Django 5.2 on 2025-05-01 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_contact_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='type',
        ),
    ]
