# Generated by Django 5.2 on 2025-05-01 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_link_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='type',
        ),
    ]
