# Generated by Django 5.2 on 2025-05-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_contact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='is_relative',
            field=models.BooleanField(default=False, help_text='勾选表示链接是相对于当前域名的路径', verbose_name='相对路径'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(help_text='可以是完整URL(如https://example.com)或相对路径(如vl/)', max_length=255, verbose_name='链接地址'),
        ),
    ]
