import os
import polib

def translate_po_file(po_file_path, translations):
    if not os.path.exists(po_file_path):
        print(f"File not found: {po_file_path}")
        return

    print(f"Processing {po_file_path}...")
    po = polib.pofile(po_file_path)
    count = 0
    for entry in po:
        if not entry.msgstr and entry.msgid in translations:
            entry.msgstr = translations[entry.msgid]
            count += 1
            if 'fuzzy' in entry.flags:
                entry.flags.remove('fuzzy')
            print(f"  Translated: '{entry.msgid}' -> '{entry.msgstr}'")
    
    if count > 0:
        po.save()
        print(f"Updated {count} translations in {po_file_path}")
    else:
        print(f"No translations updated in {po_file_path}")

# English -> Chinese (zh_Hans)
zh_hans_translations = {
    "English": "英语",
    "Japanese": "日语",
    "Traditional Chinese": "繁体中文",
    "Name (English)": "名称 (英文)",
    "Description (English)": "描述 (英文)",
    "Page Title (English)": "页面标题 (英文)",
    "Website Name (English)": "网站名称 (英文)",
    "Website Description (English)": "网站描述 (英文)",
    "Navigation Title (English)": "导航标题 (英文)",
    "Enter page title (English)": "输入页面标题 (英文)",
    "Enter navigation title (English)": "输入导航标题 (英文)",
    "Short description (English)...": "简短描述 (英文)...",
    "Content (Markdown)": "内容 (Markdown)",
    "Content (Current Language)": "内容 (当前语言)",
    "Save changes": "保存更改",
    "Save and continue editing": "保存并继续编辑",
    "Save and add another": "保存并新增",
    "Delete": "删除",
    "Cancel": "取消",
    "Search": "搜索",
    "Filter": "筛选",
    "Actions": "操作",
    "Yes, I'm sure": "是的，我确定",
    "No, take me back": "不，返回",
    "Are you sure you want to delete": "您确定要删除",
    "説明 (Japanese)": "描述 (日文)",
    "描述 (Traditional Chinese)": "描述 (繁体中文)",
    "ページタイトル (Japanese)": "页面标题 (日文)",
    "頁面標題 (Traditional Chinese)": "页面标题 (繁体中文)",
}

# Chinese -> English (en)
en_translations = {
    "内容管理": "Content Management",
    "文章": "Posts",
    "分类": "Categories",
    "标签": "Tags",
    "评论": "Comments",
    "投票": "Polls",
    "页面管理": "Page Management",
    "页面": "Pages",
    "导航": "Navigation",
    "友情链接": "Friend Links",
    "搜索占位符": "Search Placeholders",
    "系统管理": "System Management",
    "用户": "Users",
    "称号": "User Titles",
    "用户组": "User Groups",
    "日志与审计": "Logs & Audit",
    "操作日志": "Operation Logs",
    "系统日志": "System Logs",
    "维护与工具": "Maintenance & Tools",
    "系统工具": "System Tools",
    "站点设置": "Site Settings",
    "调试工具": "Debug Tools",
    "退出登录": "Logout",
    "概览": "Overview",
    "个人资料": "Profile",
    "查看站点": "View Site",
    "批量操作": "Bulk Actions",
    "确定要执行此批量操作吗？": "Are you sure you want to perform this bulk action?",
    "编辑分类": "Edit Category",
    "编辑标签": "Edit Tag",
    "编辑页面": "Edit Page",
    "编辑导航": "Edit Navigation",
    "编辑友链": "Edit Friend Link",
    "基本信息": "Basic Info",
    "外观设置": "Appearance",
    "发布": "Publish",
    "状态设置": "Status Settings",
    "保存更改": "Save Changes",
    "保存并新增": "Save and Add Another",
    "保存并继续": "Save and Continue",
    "取消": "Cancel",
    "删除": "Delete",
    "描述 (中文)": "Description (Chinese)",
    "名称 (中文)": "Name (Chinese)",
    "标题": "Title",
    "别名": "Slug",
    "内容": "Content",
    "状态": "Status",
    "创建时间": "Created At",
    "更新时间": "Updated At",
    "是否显示": "Visible",
    "排序": "Order",
    "位置": "Position",
    "链接": "URL",
    "图标": "Icon",
    "颜色": "Color",
    "页面标题 (中文)": "Page Title (Chinese)",
    "输入页面标题 (中文)": "Enter Page Title (Chinese)",
    "内容 (当前语言)": "Content (Current Language)",
    "説明 (Japanese)": "Description (Japanese)",
    "描述 (Traditional Chinese)": "Description (Traditional Chinese)",
    "ページタイトル (Japanese)": "Page Title (Japanese)",
    "頁面標題 (Traditional Chinese)": "Page Title (Traditional Chinese)",
    "输入页面标题": "Enter Page Title",
    "最新评论": "Latest Comments",
    "前": "ago",
    "这个作者很懒，什么都没写~": "This author is lazy and hasn't written anything yet~",
    "访问主页": "Visit Profile",
    "确认操作": "Confirm Action",
    "确定要执行此操作吗？": "Are you sure you want to perform this action?",
    "提示": "Notice",
    "确定": "Confirm",
    "需要密码": "Password Required",
    "文章受密码保护": "Post Password Protected",
    "该文章设置了访问密码，请输入密码继续阅读。": "This post is password protected. Please enter the password to continue reading.",
    "在此输入密码": "Enter password here",
    "验证密码": "Verify Password",
    "返回首页": "Return to Home",
    "注册": "Register",
    "注册新账号": "Register New Account",
    "加入": "Join",
    "昵称": "Nickname",
    "邮箱": "Email",
    "头像": "Avatar",
    "点击图片刷新验证码": "Click image to refresh captcha",
    "支持 JPG, PNG, WebP 格式 (推荐 1:1)": "Supports JPG, PNG, WebP (1:1 recommended)",
    "裁剪头像": "Crop Avatar",
    "请输入": "Please enter ",
    "立即注册": "Register Now",
    "已有账号？": "Already have an account?",
    "立即登录": "Login Now",
    "或": "OR",
    "搜索命令或页面…（Ctrl+K）": "Search commands or pages... (Ctrl+K)",
    "未找到匹配结果": "No results found",
    "没有找到对应的命令，请尝试更换关键词。": "No matching commands found, please try different keywords.",
    "切换": "Switch",
    "进入": "Select",
    "关闭": "Close",
    "阅读": "Reads",
    "请上传 JSON 文件": "Please upload a JSON file",
    "JSON 格式错误：根元素应为列表": "JSON format error: Root element must be a list",
    "成功导入 {count} 条数据": "Successfully imported {count} items",
    "导入失败: {error}": "Import failed: {error}",
    "通过管理后台删除": "Deleted via admin dashboard",
    "{name} 删除成功": "{name} deleted successfully",
    "发布时间": "Published At",
    "新密码": "New Password",
    "如需修改密码请在此输入，否则留空": "Enter new password to change, otherwise leave blank",
    "选项文本 (简中)": "Option Text (Simplified Chinese)",
    "选项文本 (英文)": "Option Text (English)",
    "选项文本 (日文)": "Option Text (Japanese)",
    "选项文本 (繁中)": "Option Text (Traditional Chinese)",
    "验证码": "CAPTCHA",
    "该邮箱已被注册": "This email is already registered",
    "本站目前暂停开放注册。": "Registration is currently closed.",
    "注册成功，请登录": "Registration successful, please login",
    "您的账号已被封禁，禁止登录。": "Your account has been banned.",
    "您只能编辑自己的资料": "You can only edit your own profile",
    "偏好设置已更新": "Preferences updated",
    "偏好设置更新失败": "Failed to update preferences",
    "密码修改成功": "Password changed successfully",
    "密码修改失败，请检查输入": "Failed to change password, please check input",
    "个人信息更新成功": "Profile updated successfully",
    "个人信息更新失败，请检查输入": "Failed to update profile, please check input",
    "通知已删除": "Notification deleted",
    "留言发布成功！": "Guestbook entry published successfully!",
    "请选择一个选项！": "Please select an option!",
    "查看": "View",
    "的主页": "'s Profile",
    "回复 @": "Reply to @",
    "确定要删除这条评论及其所有回复吗？": "Are you sure you want to delete this comment and all its replies?",
    "删除评论": "Delete Comment",
    "确定要删除这条回复吗？": "Are you sure you want to delete this reply?",
    "删除回复": "Delete Reply",
    "刚刚启动": "Just started",
    "天": " days",
    "小时": " hours",
    "分钟": " minutes",
    "管理员": "Admin",
    "回复": "Reply",
    "通过管理后台创建": "Created via admin dashboard",
    "通过管理后台更新": "Updated via admin dashboard",
    "更新字段: {fields}": "Updated fields: {fields}",
    "新建{name}": "New {name}",
    "编辑{name}": "Edit {name}",
    "{name} 创建成功": "{name} created successfully",
    "{name} 更新成功": "{name} updated successfully",
    "通知中心": "Notification Center",
    "浏览历史": "Browsing History",
    "个人主页": "Public Profile",
    "注销登录": "Logout",
    "偏好设置": "Settings",
    "喜欢": "Likes",
    "资料": "Info",
    "历史": "History",
    "通知": "Notifications",
    "安全": "Security",
    "设置": "Settings",
    "搜索...": "Search...",
    "项已选择": "items selected",
    "表单错误": "Form Errors",
    "全站搜索": "Global Search",
    "未找到相关结果": "No results found",
    "搜索文章、标签、分类...": "Search posts, tags, categories...",
    "Rosetta Dashboard": "Rosetta Dashboard",
    "Hello,": "Hello,",
    "欢迎回到 Rosetta 控制台。这里是您的数字指挥中心。": "Welcome back to Rosetta Dashboard. This is your digital command center.",
    "写文章": "Write Post",
    "总文章数": "Total Posts",
    "较上月": "vs last month",
    "总评论数": "Total Comments",
    "待审": "Pending",
    "全部已审": "All Approved",
    "系统健康度": "System Health",
    "运行正常": "Operational",
    "快捷操作": "Quick Actions",
    "清理缓存": "Clear Cache",
    "活跃趋势": "Activity Trend",
    "评论分布": "Comment Distribution",
    "已发布": "Published",
    "待审核": "Pending Review",
    "热门文章 TOP 5": "Top 5 Posts",
    "分类分布": "Category Distribution",
    "热门标签": "Popular Tags",
    "最近评论": "Recent Comments",
    "查看全部": "View All",
    "暂无活动": "No recent activity",
    "系统状态": "System Status",
    "CPU": "CPU",
    # Additional translations
    "知识库": "Knowledge Base",
    "全部文章": "All Posts",
    "共收录": "Collected",
    "篇文章": " posts",
    "网格视图": "Grid View",
    "列表视图": "List View",
    "暂无文章": "No Posts",
    "这里还是一片荒原，等待知识的种子发芽。": "It's still a wasteland here, waiting for the seeds of knowledge to sprout.",
    "上一页": "Previous",
    "下一页": "Next",
    "文章归档": "Archives",
    "时光轴": "Timeline",
    "共": "Total",
    "篇文章，记录成长的足迹。": " posts, recording the footprints of growth.",
    "暂无历史文章": "No historical posts",
    "开始创作，记录第一笔足迹吧！": "Start creating and record your first footprint!",
    "探索知识库": "Explore Knowledge Base",
    "内容分类": "Categories",
    "按照主题探索文章，发现感兴趣的领域。我们为您精心整理了": "Explore articles by topic and discover areas of interest. We have carefully curated for you",
    "个分类。": " categories.",
    "搜索感兴趣的分类...": "Search categories...",
    "暂无分类": "No Categories",
    "还没有添加任何分类，或者没有找到匹配的结果。": "No categories added yet, or no matching results found.",
    "Explore": "Explore",
    "话题索引": "Topic Index",
    "标签云": "Tag Cloud",
    "探索": "Explore",
    "个精彩话题，发现更多相关内容。": " exciting topics, discover more related content.",
    "查找标签...": "Search tags...",
    "暂无标签": "No Tags",
    "置顶": "Pinned",
    "最新": "New",
    "敬请期待更多精彩内容！": "Stay tuned for more exciting content!",
    "分钟阅读": " min read",
    "分享": "Share",
    "分享到 X": "Share to X",
    "链接已复制！": "Link copied!",
    "复制链接": "Copy Link",
    "相关阅读": "Related Reading",
    "上一篇": "Previous Post",
    "下一篇": "Next Post",
    "评论已关闭": "Comments Closed",
    "管理员已暂时关闭评论功能。": "Comments are temporarily closed by admin.",
    "正在回复": "Replying to",
    "取消回复": "Cancel Reply",
    "发布评论": "Post Comment",
    "需要登录": "Login Required",
    "发表你的观点": "Express your opinion",
    "你的观点很有价值，快来抢沙发吧！": "Your opinion is valuable, be the first to comment!",
    "目录": "Table of Contents",
    "仅显示最近20条记录": "Only show last 20 records",
    "文章标题": "Article Title",
    "浏览时间": "Viewed At",
    "消息通知": "Notifications",
    "标为已读": "Mark as Read",
    "暂无新通知": "No new notifications",
    "账号安全": "Account Security",
    "界面主题": "Interface Theme",
    "暗黑模式": "Dark Mode",
    "切换明亮/暗黑主题": "Switch Light/Dark Theme",
    "公开个人资料": "Public Profile",
    "允许其他人查看您的个人资料和浏览历史": "Allow others to view your profile and browsing history",
    "保存设置": "Save Settings",
    "建议尺寸 1200x300px，支持拖拽上传": "Recommended size 1200x300px, drag and drop supported",
    "简短的自我介绍": "Short bio",
    "输入关键词...": "Enter keywords...",
    "没有找到相关结果": "No results found",
    "请尝试其他关键词或切换搜索类型。": "Please try other keywords or switch search type.",
    "取消置顶": "Unpin",
    "置顶文章": "Pin Post",
}

# Chinese -> Japanese (ja)
ja_translations = {
    "内容管理": "コンテンツ管理",
    "文章": "記事",
    "分类": "カテゴリー",
    "标签": "タグ",
    "评论": "コメント",
    "投票": "投票",
    "页面管理": "ページ管理",
    "页面": "ページ",
    "导航": "ナビゲーション",
    "友情链接": "リンク",
    "系统管理": "系统管理",
    "用户": "ユーザー",
    "称号": "称号",
    "用户组": "ユーザーグループ",
    "日志与审计": "ログと監査",
    "退出登录": "ログアウト",
    "保存更改": "変更を保存",
    "概览": "概要",
    "名称": "名前",
    "描述": "説明",
    "标题": "タイトル",
    "内容": "内容",
    "最新评论": "最新のコメント",
    "前": "前",
    "这个作者很懒，什么都没写~": "この著者は怠け者で、何も書いていません〜",
    "访问主页": "プロフィールを見る",
    "确认操作": "操作の確認",
    "确定要执行此操作吗？": "この操作を実行してもよろしいですか？",
    "提示": "ヒント",
    "确定": "確認",
    "取消": "キャンセル",
    "需要密码": "パスワードが必要です",
    "文章受密码保护": "記事はパスワードで保護されています",
    "该文章设置了访问密码，请输入密码继续阅读。": "この記事はパスワードで保護されています。続きを読むにはパスワードを入力してください。",
    "在此输入密码": "パスワードを入力",
    "验证密码": "パスワードを認証",
    "返回首页": "ホームに戻る",
    "注册": "登録",
    "注册新账号": "新規アカウント登録",
    "加入": "参加する",
    "昵称": "ニックネーム",
    "邮箱": "メールアドレス",
    "头像": "アバター",
    "点击图片刷新验证码": "画像をクリックして認証コードを更新",
    "支持 JPG, PNG, WebP 格式 (推荐 1:1)": "JPG, PNG, WebP形式をサポート (1:1推奨)",
    "裁剪头像": "アバターを切り抜く",
    "请输入": "入力してください：",
    "立即注册": "今すぐ登録",
    "已有账号？": "すでにアカウントをお持ちですか？",
    "立即登录": "今すぐログイン",
    "或": "または",
    "搜索命令或页面…（Ctrl+K）": "コマンドまたはページを検索... (Ctrl+K)",
    "未找到匹配结果": "一致する結果が見つかりません",
    "没有找到对应的命令，请尝试更换关键词。": "一致するコマンドが見つかりません。別のキーワードを試してください。",
    "切换": "切り替え",
    "进入": "選択",
    "关闭": "閉じる",
    "阅读": "閲覧",
    "请上传 JSON 文件": "JSONファイルをアップロードしてください",
    "JSON 格式错误：根元素应为列表": "JSON形式エラー：ルート要素はリストである必要があります",
    "成功导入 {count} 条数据": "{count} 件のデータをインポートしました",
    "导入失败: {error}": "インポートに失敗しました: {error}",
    "通过管理后台删除": "管理ダッシュボード経由で削除",
    "{name} 删除成功": "{name} を削除しました",
    "发布时间": "公開日時",
    "新密码": "新しいパスワード",
    "如需修改密码请在此输入，否则留空": "パスワードを変更する場合は入力してください。変更しない場合は空欄にしてください",
    "选项文本 (简中)": "選択肢テキスト (簡体字)",
    "选项文本 (英文)": "選択肢テキスト (英語)",
    "选项文本 (日文)": "選択肢テキスト (日本語)",
    "选项文本 (繁中)": "選択肢テキスト (繁体字)",
    "验证码": "認証コード",
    "该邮箱已被注册": "このメールアドレスは既に登録されています",
    "本站目前暂停开放注册。": "現在、新規登録は停止されています。",
    "注册成功，请登录": "登録が完了しました。ログインしてください",
    "您的账号已被封禁，禁止登录。": "アカウントが停止されているため、ログインできません。",
    "您只能编辑自己的资料": "自分のプロフィールのみ編集できます",
    "偏好设置已更新": "設定を更新しました",
    "偏好设置更新失败": "設定の更新に失敗しました",
    "密码修改成功": "パスワードを変更しました",
    "密码修改失败，请检查输入": "パスワードの変更に失敗しました。入力を確認してください",
    "个人信息更新成功": "プロフィールを更新しました",
    "个人信息更新失败，请检查输入": "プロフィールの更新に失敗しました。入力を確認してください",
    "通知已删除": "通知を削除しました",
    "留言发布成功！": "メッセージを投稿しました！",
    "请选择一个选项！": "選択肢を選んでください！",
    "查看": "表示",
    "的主页": "のプロフィール",
    "回复 @": "@に返信",
    "确定要删除这条评论及其所有回复吗？": "このコメントとすべての返信を削除してもよろしいですか？",
    "删除评论": "コメントを削除",
    "确定要删除这条回复吗？": "この返信を削除してもよろしいですか？",
    "删除回复": "返信を削除",
    "刚刚启动": "起動したばかり",
    "天": "日",
    "小时": "時間",
    "分钟": "分",
    "管理员": "管理者",
    "回复": "返信",
    "通过管理后台创建": "管理ダッシュボード経由で作成",
    "通过管理后台更新": "管理ダッシュボード経由で更新",
    "更新字段: {fields}": "更新フィールド: {fields}",
    "新建{name}": "新規{name}",
    "编辑{name}": "{name}を編集",
    "{name} 创建成功": "{name} を作成しました",
    "{name} 更新成功": "{name} を更新しました",
    "通知中心": "通知センター",
    "浏览历史": "閲覧履歴",
    "个人主页": "マイページ",
    "注销登录": "ログアウト",
    "偏好设置": "設定",
    "喜欢": "いいね",
    "资料": "プロフィール",
    "历史": "履歴",
    "通知": "通知",
    "安全": "セキュリティ",
    "设置": "設定",
    "搜索...": "検索...",
    "项已选择": "項目を選択しました",
    "表单错误": "フォームエラー",
    "全站搜索": "サイト内検索",
    "未找到相关结果": "結果が見つかりません",
    "搜索文章、标签、分类...": "記事、タグ、カテゴリを検索...",
    "Rosetta Dashboard": "Rosetta ダッシュボード",
    "Hello,": "こんにちは、",
    "欢迎回到 Rosetta 控制台。这里是您的数字指挥中心。": "Rosetta コンソールへようこそ。ここはあなたのデジタル指令センターです。",
    "写文章": "記事を書く",
    "总文章数": "総記事数",
    "较上月": "先月比",
    "总评论数": "総コメント数",
    "待审": "承認待ち",
    "全部已审": "すべて承認済み",
    "系统健康度": "システム健全性",
    "运行正常": "正常稼働中",
    "快捷操作": "クイックアクション",
    "清理缓存": "キャッシュクリア",
    "活跃趋势": "アクティビティ傾向",
    "评论分布": "コメント分布",
    "已发布": "公開済み",
    "待审核": "承認待ち",
    "热门文章 TOP 5": "人気記事 TOP 5",
    "分类分布": "カテゴリ分布",
    "热门标签": "人気タグ",
    "最近评论": "最近のコメント",
    "查看全部": "すべて見る",
    "暂无活动": "最近のアクティビティはありません",
    "系统状态": "システムステータス",
    "CPU": "CPU",
    # Additional translations
    "知识库": "ナレッジベース",
    "全部文章": "すべての記事",
    "共收录": "収録数",
    "篇文章": " 記事",
    "网格视图": "グリッド表示",
    "列表视图": "リスト表示",
    "暂无文章": "記事がありません",
    "这里还是一片荒原，等待知识的种子发芽。": "ここはまだ荒野です。知識の種が芽吹くのを待っています。",
    "上一页": "前へ",
    "下一页": "次へ",
    "文章归档": "アーカイブ",
    "时光轴": "タイムライン",
    "共": "合計",
    "篇文章，记录成长的足迹。": " 記事、成長の足跡を記録。",
    "暂无历史文章": "履歴記事がありません",
    "开始创作，记录第一笔足迹吧！": "創作を始めて、最初の足跡を記録しましょう！",
    "探索知识库": "ナレッジベースを探索",
    "内容分类": "カテゴリー",
    "按照主题探索文章，发现感兴趣的领域。我们为您精心整理了": "テーマ別に記事を探索し、興味のある分野を見つけましょう。厳選された",
    "个分类。": " 個のカテゴリーがあります。",
    "搜索感兴趣的分类...": "カテゴリーを検索...",
    "暂无分类": "カテゴリーがありません",
    "还没有添加任何分类，或者没有找到匹配的结果。": "カテゴリーが追加されていないか、一致する結果が見つかりませんでした。",
    "Explore": "探索",
    "话题索引": "トピックインデックス",
    "标签云": "タグクラウド",
    "探索": "探索",
    "个精彩话题，发现更多相关内容。": " 個のトピック、関連コンテンツを発見。",
    "查找标签...": "タグを検索...",
    "暂无标签": "タグがありません",
    "置顶": "固定",
    "最新": "最新",
    "敬请期待更多精彩内容！": "さらなる素晴らしいコンテンツにご期待ください！",
    "分钟阅读": " 分で読める",
    "分享": "共有",
    "分享到 X": "Xで共有",
    "链接已复制！": "リンクをコピーしました！",
    "复制链接": "リンクをコピー",
    "相关阅读": "関連記事",
    "上一篇": "前の記事",
    "下一篇": "次の記事",
    "评论已关闭": "コメントは閉じられました",
    "管理员已暂时关闭评论功能。": "管理者がコメント機能を一時的に停止しています。",
    "正在回复": "返信中",
    "取消回复": "返信をキャンセル",
    "发布评论": "コメントを投稿",
    "需要登录": "ログインが必要です",
    "发表你的观点": "意見を投稿する",
    "你的观点很有价值，快来抢沙发吧！": "あなたの意見は貴重です。最初のコメントを投稿しましょう！",
    "目录": "目次",
    "仅显示最近20条记录": "最近の20件のみ表示",
    "文章标题": "記事タイトル",
    "浏览时间": "閲覧日時",
    "消息通知": "通知",
    "标为已读": "既読にする",
    "暂无新通知": "新しい通知はありません",
    "账号安全": "アカウントセキュリティ",
    "界面主题": "テーマ設定",
    "暗黑模式": "ダークモード",
    "切换明亮/暗黑主题": "ライト/ダークテーマを切り替え",
    "公开个人资料": "プロフィールを公開",
    "允许其他人查看您的个人资料和浏览历史": "他のユーザーがあなたのプロフィールと閲覧履歴を見ることを許可します",
    "保存设置": "設定を保存",
    "建议尺寸 1200x300px，支持拖拽上传": "推奨サイズ 1200x300px、ドラッグ＆ドロップ対応",
    "简短的自我介绍": "短い自己紹介",
    "请输入": "入力してください",
    "输入关键词...": "キーワードを入力...",
    "没有找到相关结果": "結果が見つかりません",
    "请尝试其他关键词或切换搜索类型。": "他のキーワードを試すか、検索タイプを切り替えてください。",
    "取消置顶": "固定解除",
    "置顶文章": "記事を固定",
}

# Chinese -> Traditional Chinese (zh_Hant)
zh_hant_translations = {
    "内容管理": "內容管理",
    "文章": "文章",
    "分类": "分類",
    "标签": "標籤",
    "评论": "評論",
    "投票": "投票",
    "页面管理": "頁面管理",
    "页面": "頁面",
    "导航": "導航",
    "友情链接": "友情鏈接",
    "系统管理": "系統管理",
    "用户": "用戶",
    "称号": "稱號",
    "用户组": "用戶組",
    "日志与审计": "日誌與審計",
    "退出登录": "退出登錄",
    "保存更改": "保存更改",
    "概览": "概覽",
    "名称": "名稱",
    "描述": "描述",
    "标题": "標題",
    "内容": "內容",
    "最新评论": "最新評論",
    "前": "前",
    "这个作者很懒，什么都没写~": "這個作者很懶，什麼都沒寫~",
    "访问主页": "訪問主頁",
    "确认操作": "確認操作",
    "确定要执行此操作吗？": "確定要執行此操作嗎？",
    "提示": "提示",
    "确定": "確定",
    "取消": "取消",
    "需要密码": "需要密碼",
    "文章受密码保护": "文章受密碼保護",
    "该文章设置了访问密码，请输入密码繼續阅读。": "該文章設置了訪問密碼，請輸入密碼繼續閱讀。",
    "在此输入密码": "在此輸入密碼",
    "验证密码": "驗證密碼",
    "返回首页": "返回首頁",
    "注册": "註冊",
    "注册新账号": "註冊新帳號",
    "加入": "加入",
    "昵称": "暱稱",
    "邮箱": "郵箱",
    "头像": "頭像",
    "点击图片刷新验证码": "點擊圖片刷新驗證碼",
    "支持 JPG, PNG, WebP 格式 (推荐 1:1)": "支持 JPG, PNG, WebP 格式 (推薦 1:1)",
    "裁剪头像": "裁剪頭像",
    "请输入": "請輸入",
    "立即注册": "立即註冊",
    "已有账号？": "已有帳號？",
    "立即登录": "立即登錄",
    "或": "或",
    "搜索命令或页面…（Ctrl+K）": "搜索命令或頁面…（Ctrl+K）",
    "未找到匹配结果": "未找到匹配結果",
    "没有找到对应的命令，请尝试更换关键词。": "沒有找到對應的命令，請嘗試更換關鍵詞。",
    "切换": "切換",
    "进入": "進入",
    "关闭": "關閉",
    "阅读": "閱讀",
    "请上传 JSON 文件": "請上傳 JSON 文件",
    "JSON 格式错误：根元素应为列表": "JSON 格式錯誤：根元素應為列表",
    "成功导入 {count} 条数据": "成功導入 {count} 條數據",
    "导入失败: {error}": "導入失敗: {error}",
    "通过管理后台删除": "通過管理後台刪除",
    "{name} 删除成功": "{name} 刪除成功",
    "发布时间": "發布時間",
    "新密码": "新密碼",
    "如需修改密码请在此输入，否则留空": "如需修改密碼請在此輸入，否則留空",
    "选项文本 (简中)": "選項文本 (簡中)",
    "选项文本 (英文)": "選項文本 (英文)",
    "选项文本 (日文)": "選項文本 (日文)",
    "选项文本 (繁中)": "選項文本 (繁中)",
    "验证码": "驗證碼",
    "该邮箱已被注册": "該郵箱已被註冊",
    "本站目前暂停开放注册。": "本站目前暫停開放註冊。",
    "注册成功，请登录": "註冊成功，請登錄",
    "您的账号已被封禁，禁止登录。": "您的帳號已被封禁，禁止登錄。",
    "您只能编辑自己的资料": "您只能編輯自己的資料",
    "偏好设置已更新": "偏好設置已更新",
    "偏好设置更新失败": "偏好設置更新失敗",
    "密码修改成功": "密碼修改成功",
    "密码修改失败，请检查输入": "密碼修改失敗，請檢查輸入",
    "个人信息更新成功": "個人信息更新成功",
    "个人信息更新失败，请检查输入": "個人信息更新失敗，請檢查輸入",
    "通知已删除": "通知已刪除",
    "留言发布成功！": "留言發布成功！",
    "请选择一个选项！": "請選擇一個選項！",
    "查看": "查看",
    "的主页": "的主頁",
    "回复 @": "回覆 @",
    "确定要删除这条评论及其所有回复吗？": "確定要刪除這條評論及其所有回覆嗎？",
    "删除评论": "刪除評論",
    "确定要删除这条回复吗？": "確定要刪除這條回覆嗎？",
    "删除回复": "刪除回覆",
    "刚刚启动": "剛剛啟動",
    "天": "天",
    "小时": "小時",
    "分钟": "分鐘",
    "管理员": "管理員",
    "回复": "回覆",
    "通过管理后台创建": "通過管理後台創建",
    "通过管理后台更新": "通過管理後台更新",
    "更新字段: {fields}": "更新字段: {fields}",
    "新建{name}": "新建{name}",
    "编辑{name}": "編輯{name}",
    "{name} 创建成功": "{name} 創建成功",
    "{name} 更新成功": "{name} 更新成功",
    "通知中心": "通知中心",
    "浏览历史": "瀏覽歷史",
    "个人主页": "個人主頁",
    "注销登录": "登出",
    "偏好设置": "偏好設置",
    "喜欢": "喜歡",
    "资料": "資料",
    "历史": "歷史",
    "通知": "通知",
    "安全": "安全",
    "设置": "設置",
    "搜索...": "搜索...",
    "项已选择": "項已選擇",
    "表单错误": "表單錯誤",
    "全站搜索": "全站搜索",
    "未找到相关结果": "未找到相關結果",
    "搜索文章、标签、分类...": "搜索文章、標籤、分類...",
    "Rosetta Dashboard": "Rosetta 控制台",
    "Hello,": "你好，",
    "欢迎回到 Rosetta 控制台。这里是您的数字指挥中心。": "歡迎回到 Rosetta 控制台。這裡是您的數字指揮中心。",
    "写文章": "寫文章",
    "总文章数": "總文章數",
    "较上月": "較上月",
    "总评论数": "總評論數",
    "待审": "待審",
    "全部已审": "全部已審",
    "系统健康度": "系統健康度",
    "运行正常": "運行正常",
    "快捷操作": "快捷操作",
    "清理缓存": "清理緩存",
    "活跃趋势": "活躍趨勢",
    "评论分布": "評論分佈",
    "已发布": "已發布",
    "待审核": "待審核",
    "热门文章 TOP 5": "熱門文章 TOP 5",
    "分类分布": "分類分佈",
    "热门标签": "熱門標籤",
    "最近评论": "最近評論",
    "查看全部": "查看全部",
    "暂无活动": "暫無活動",
    "系统状态": "系統狀態",
    "CPU": "CPU",
    # Additional translations
    "知识库": "知識庫",
    "全部文章": "全部文章",
    "共收录": "共收錄",
    "篇文章": " 篇文章",
    "网格视图": "網格視圖",
    "列表视图": "列表視圖",
    "暂无文章": "暫無文章",
    "这里还是一片荒原，等待知识的种子发芽。": "這裡還是一片荒原，等待知識的種子發芽。",
    "上一页": "上一頁",
    "下一页": "下一頁",
    "文章归档": "文章歸檔",
    "时光轴": "時光軸",
    "共": "共",
    "篇文章，记录成长的足迹。": " 篇文章，記錄成長的足跡。",
    "暂无历史文章": "暫無歷史文章",
    "开始创作，记录第一笔足迹吧！": "開始創作，記錄第一筆足跡吧！",
    "探索知识库": "探索知識庫",
    "内容分类": "內容分類",
    "按照主题探索文章，发现感兴趣的领域。我们为您精心整理了": "按照主題探索文章，發現感興趣的領域。我們為您精心整理了",
    "个分类。": " 個分類。",
    "搜索感兴趣的分类...": "搜索感興趣的分類...",
    "暂无分类": "暫無分類",
    "还没有添加任何分类，或者没有找到匹配的结果。": "還沒有添加任何分類，或者沒有找到匹配的結果。",
    "Explore": "Explore",
    "话题索引": "話題索引",
    "标签云": "標籤雲",
    "探索": "探索",
    "个精彩话题，发现更多相关内容。": " 個精彩話題，發現更多相關內容。",
    "查找标签...": "查找標籤...",
    "暂无标签": "暫無標籤",
    "置顶": "置頂",
    "最新": "最新",
    "敬请期待更多精彩内容！": "敬請期待更多精彩內容！",
    "分钟阅读": " 分鐘閱讀",
    "分享": "分享",
    "分享到 X": "分享到 X",
    "链接已复制！": "鏈接已複製！",
    "复制链接": "複製鏈接",
    "相关阅读": "相關閱讀",
    "上一篇": "上一篇",
    "下一篇": "下一篇",
    "评论已关闭": "評論已關閉",
    "管理员已暂时关闭评论功能。": "管理員已暫時關閉評論功能。",
    "正在回复": "正在回覆",
    "取消回复": "取消回覆",
    "发布评论": "發布評論",
    "需要登录": "需要登錄",
    "发表你的观点": "發表你的觀點",
    "你的观点很有价值，快来抢沙发吧！": "你的觀點很有價值，快來搶沙發吧！",
    "目录": "目錄",
    "仅显示最近20条记录": "僅顯示最近20條記錄",
    "文章标题": "文章標題",
    "浏览时间": "瀏覽時間",
    "消息通知": "消息通知",
    "标为已读": "標為已讀",
    "暂无新通知": "暫無新通知",
    "账号安全": "帳號安全",
    "界面主题": "界面主題",
    "暗黑模式": "暗黑模式",
    "切换明亮/暗黑主题": "切換明亮/暗黑主題",
    "公开个人资料": "公開個人資料",
    "允许其他人查看您的个人资料和浏览历史": "允許其他人查看您的個人資料和瀏覽歷史",
    "保存设置": "保存設置",
    "建议尺寸 1200x300px，支持拖拽上传": "建議尺寸 1200x300px，支持拖拽上傳",
    "简短的自我介绍": "簡短的自我介紹",
    "请输入": "請輸入",
    "输入关键词...": "輸入關鍵詞...",
    "没有找到相关结果": "沒有找到相關結果",
    "请尝试其他关键词或切换搜索类型。": "請嘗試其他關鍵詞或切換搜索類型。",
    "取消置顶": "取消置頂",
    "置顶文章": "置頂文章",
}

if __name__ == "__main__":
    base_dir = os.getcwd()
    zh_hans_po = os.path.join(base_dir, "locale", "zh_Hans", "LC_MESSAGES", "django.po")
    en_po = os.path.join(base_dir, "locale", "en", "LC_MESSAGES", "django.po")
    ja_po = os.path.join(base_dir, "locale", "ja", "LC_MESSAGES", "django.po")
    zh_hant_po = os.path.join(base_dir, "locale", "zh_Hant", "LC_MESSAGES", "django.po")
    
    translate_po_file(zh_hans_po, zh_hans_translations)
    translate_po_file(en_po, en_translations)
    translate_po_file(ja_po, ja_translations)
    translate_po_file(zh_hant_po, zh_hant_translations)
