# Generated by Django 6.0 on 2026-01-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="text_en",
            field=models.CharField(max_length=200, null=True, verbose_name="选项文本"),
        ),
        migrations.AddField(
            model_name="choice",
            name="text_ja",
            field=models.CharField(max_length=200, null=True, verbose_name="选项文本"),
        ),
        migrations.AddField(
            model_name="choice",
            name="text_zh_hans",
            field=models.CharField(max_length=200, null=True, verbose_name="选项文本"),
        ),
        migrations.AddField(
            model_name="choice",
            name="text_zh_hant",
            field=models.CharField(max_length=200, null=True, verbose_name="选项文本"),
        ),
        migrations.AddField(
            model_name="poll",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="描述"),
        ),
        migrations.AddField(
            model_name="poll",
            name="description_ja",
            field=models.TextField(blank=True, null=True, verbose_name="描述"),
        ),
        migrations.AddField(
            model_name="poll",
            name="description_zh_hans",
            field=models.TextField(blank=True, null=True, verbose_name="描述"),
        ),
        migrations.AddField(
            model_name="poll",
            name="description_zh_hant",
            field=models.TextField(blank=True, null=True, verbose_name="描述"),
        ),
        migrations.AddField(
            model_name="poll",
            name="title_en",
            field=models.CharField(max_length=200, null=True, verbose_name="标题"),
        ),
        migrations.AddField(
            model_name="poll",
            name="title_ja",
            field=models.CharField(max_length=200, null=True, verbose_name="标题"),
        ),
        migrations.AddField(
            model_name="poll",
            name="title_zh_hans",
            field=models.CharField(max_length=200, null=True, verbose_name="标题"),
        ),
        migrations.AddField(
            model_name="poll",
            name="title_zh_hant",
            field=models.CharField(max_length=200, null=True, verbose_name="标题"),
        ),
    ]
