"""Add visibility field to Post model

Revision ID: 0482c6771d47
Revises: 5182cb36811d
Create Date: 2026-02-18 20:49:08.774742

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0482c6771d47"
down_revision: str | None = "5182cb36811d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """升级数据库"""
    # 先添加可空的列
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("visibility", sa.String(length=10), nullable=True))

    # 更新所有 NULL 值为 'public'
    op.execute("UPDATE posts SET visibility = 'public' WHERE visibility IS NULL")

    # 再设置为 NOT NULL
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.alter_column("visibility", nullable=False)


def downgrade() -> None:
    """回退数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.drop_column("visibility")

    # ### end Alembic commands ###
