"""add_default_post_cover_to_site_config

Revision ID: 1e26faaeeb6b
Revises: a1576082c8a6
Create Date: 2026-02-18 05:23:01.633953

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "1e26faaeeb6b"
down_revision: str | None = "a1576082c8a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """回退数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
