"""add_private_messages_and_social_links

Revision ID: 3e16398564fc
Revises: 0482c6771d47
Create Date: 2026-02-19 22:28:10.501251

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3e16398564fc"
down_revision: str | None = "0482c6771d47"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "private_messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=False, comment="发送者ID"),
        sa.Column("recipient_id", sa.Integer(), nullable=False, comment="接收者ID"),
        sa.Column("content", sa.Text(), nullable=False, comment="消息内容"),
        sa.Column("is_read", sa.Boolean(), nullable=False, comment="是否已读"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.ForeignKeyConstraint(["recipient_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sender_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("private_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_private_messages_recipient_id"), ["recipient_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_private_messages_sender_id"), ["sender_id"], unique=False
        )

    with op.batch_alter_table("user_preferences", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("show_email", sa.Boolean(), nullable=False, comment="是否显示邮箱")
        )
        batch_op.add_column(
            sa.Column("show_posts", sa.Boolean(), nullable=False, comment="是否显示文章列表")
        )
        batch_op.add_column(
            sa.Column("show_comments", sa.Boolean(), nullable=False, comment="是否显示评论列表")
        )
        batch_op.add_column(
            sa.Column("show_stats", sa.Boolean(), nullable=False, comment="是否显示统计数据")
        )
        batch_op.add_column(
            sa.Column("show_social_links", sa.Boolean(), nullable=False, comment="是否显示社交链接")
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """回退数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_preferences", schema=None) as batch_op:
        batch_op.drop_column("show_social_links")
        batch_op.drop_column("show_stats")
        batch_op.drop_column("show_comments")
        batch_op.drop_column("show_posts")
        batch_op.drop_column("show_email")

    with op.batch_alter_table("private_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_private_messages_sender_id"))
        batch_op.drop_index(batch_op.f("ix_private_messages_recipient_id"))

    op.drop_table("private_messages")
    # ### end Alembic commands ###
