"""添加 Webhook、收藏、验证码、修订版本等表

Revision ID: 5182cb36811d
Revises: da64932d8748
Create Date: 2026-02-18 13:16:52.577787

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "5182cb36811d"
down_revision: str | None = "da64932d8748"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """回退数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
