"""添加修订版本、操作日志和回收站表

Revision ID: cdbb46311155
Revises: 1e26faaeeb6b
Create Date: 2026-02-18 12:36:50.098644

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cdbb46311155"
down_revision: str | None = "1e26faaeeb6b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operation_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("resource_type", sa.String(length=50), nullable=False),
        sa.Column("resource_id", sa.Integer(), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("request_path", sa.String(length=500), nullable=True),
        sa.Column("request_method", sa.String(length=10), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("operation_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_operation_logs_action"), ["action"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_operation_logs_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_operation_logs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "trash_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("resource_type", sa.String(length=50), nullable=False),
        sa.Column("resource_id", sa.Integer(), nullable=False),
        sa.Column("resource_data", sa.Text(), nullable=False),
        sa.Column("deleted_by_id", sa.Integer(), nullable=True),
        sa.Column("auto_delete_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["deleted_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("trash_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_trash_items_resource_type"), ["resource_type"], unique=False
        )

    op.create_table(
        "post_revisions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=True),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column("change_summary", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("post_revisions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_post_revisions_post_id"), ["post_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """回退数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post_revisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_post_revisions_post_id"))

    op.drop_table("post_revisions")
    with op.batch_alter_table("trash_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_trash_items_resource_type"))

    op.drop_table("trash_items")
    with op.batch_alter_table("operation_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_operation_logs_user_id"))
        batch_op.drop_index(batch_op.f("ix_operation_logs_created_at"))
        batch_op.drop_index(batch_op.f("ix_operation_logs_action"))

    op.drop_table("operation_logs")
    # ### end Alembic commands ###
