# Generated by Django 5.2 on 2025-05-05 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('url', models.CharField(max_length=255, verbose_name='链接')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome 图标类名，例如: fa-home', max_length=50, verbose_name='图标')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_external', models.BooleanField(default=False, help_text='选中则在新窗口打开', verbose_name='是否外部链接')),
                ('position', models.CharField(choices=[('header', '页眉'), ('footer', '页脚'), ('sidebar', '侧栏')], default='header', max_length=20, verbose_name='位置')),
                ('color', models.CharField(choices=[('blue', '蓝色'), ('red', '红色'), ('green', '绿色'), ('purple', '紫色'), ('yellow', '黄色'), ('pink', '粉色'), ('indigo', '靛青色'), ('gray', '灰色'), ('teal', '蓝绿色'), ('orange', '橙色'), ('cyan', '青色'), ('lime', '酸橙色'), ('amber', '琥珀色'), ('emerald', '祖母绿'), ('rose', '玫瑰色'), ('sky', '天空蓝'), ('violet', '紫罗兰色')], default='blue', max_length=20, verbose_name='颜色')),
                ('mobile_only', models.BooleanField(default=False, verbose_name='仅在移动端显示')),
                ('desktop_only', models.BooleanField(default=False, verbose_name='仅在桌面端显示')),
                ('css_class', models.CharField(blank=True, help_text='自定义CSS类', max_length=100, verbose_name='CSS类')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='navigation.navigation', verbose_name='父级菜单')),
            ],
            options={
                'verbose_name': '导航项',
                'verbose_name_plural': '导航管理',
                'ordering': ['position', 'order', 'id'],
            },
        ),
    ]
