# Generated by Django 5.2 on 2025-05-05 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('url', models.CharField(max_length=200, verbose_name='链接')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome 图标类名，例如: fas fa-home', max_length=50, verbose_name='图标')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('target_blank', models.BooleanField(default=False, verbose_name='新窗口打开')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='navigation.navigationitem', verbose_name='父级菜单')),
            ],
            options={
                'verbose_name': '导航项',
                'verbose_name_plural': '导航项',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='Navigation',
        ),
    ]
