# Generated by Django 6.0 on 2026-01-27 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestbookEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(blank=True, max_length=50, verbose_name="昵称"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="邮箱"),
                ),
                ("website", models.URLField(blank=True, verbose_name="网站")),
                ("content", models.TextField(verbose_name="内容")),
                ("is_public", models.BooleanField(default=True, verbose_name="公开")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "reply_content",
                    models.TextField(blank=True, verbose_name="回复内容"),
                ),
                (
                    "reply_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="回复时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "留言",
                "verbose_name_plural": "留言",
                "ordering": ["-created_at"],
            },
        ),
    ]
