# Generated by Django 6.0 on 2026-01-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guestbook", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestbookentry",
            name="show_email",
            field=models.BooleanField(default=False, verbose_name="显示邮箱"),
        ),
    ]
