# Generated by Django 6.0 on 2026-01-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guestbook", "0002_guestbookentry_show_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guestbookentry",
            options={
                "ordering": ["-is_pinned", "-created_at"],
                "verbose_name": "留言",
                "verbose_name_plural": "留言",
            },
        ),
        migrations.AddField(
            model_name="guestbookentry",
            name="is_pinned",
            field=models.BooleanField(default=False, verbose_name="置顶"),
        ),
    ]
