# Generated by Django 6.0 on 2026-01-28 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guestbook", "0003_alter_guestbookentry_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guestbookentry",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "留言",
                "verbose_name_plural": "留言",
            },
        ),
        migrations.RemoveField(
            model_name="guestbookentry",
            name="is_pinned",
        ),
    ]
