# Generated by Django 5.2 on 2025-04-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='网站名称')),
                ('url', models.URLField(verbose_name='网站地址')),
                ('description', models.TextField(verbose_name='网站描述')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_invalid', models.BooleanField(default=False, verbose_name='是否失效')),
            ],
            options={
                'verbose_name': '视频网站',
                'verbose_name_plural': '视频网站',
            },
        ),
    ]
