# Generated by Django 5.2 on 2025-04-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosite',
            name='category',
            field=models.CharField(choices=[('movie', '影视'), ('anime', '动漫')], default='movie', max_length=10, verbose_name='分类'),
        ),
    ]
