# Generated by Django 5.2 on 2025-06-08 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videolist', '0003_alter_videosite_options_alter_videosite_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosite',
            name='pv',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='浏览次数'),
        ),
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('last_viewed', models.DateTimeField(auto_now=True, verbose_name='最后浏览时间')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='videolist.videosite', verbose_name='视频站点')),
            ],
            options={
                'verbose_name': '视频站点浏览记录',
                'verbose_name_plural': '视频站点浏览记录',
                'ordering': ['-last_viewed'],
            },
        ),
    ]
