# Generated by Django 5.2 on 2025-06-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videolist', '0004_videosite_pv_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_date', models.DateTimeField(auto_now_add=True, verbose_name='浏览日期')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户代理')),
            ],
            options={
                'verbose_name': '网站访问记录',
            },
        ),
        migrations.RemoveField(
            model_name='videosite',
            name='pv',
        ),
        migrations.AddField(
            model_name='views',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址'),
        ),
        migrations.AddField(
            model_name='views',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='用户代理'),
        ),
    ]
