# Generated by Django 5.2 on 2025-06-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videolist', '0005_siteview_remove_videosite_pv_views_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosite',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='浏览次数'),
        ),
        migrations.DeleteModel(
            name='Views',
        ),
    ]
